### ISSUE TITLE
Put the links in unordered list instead of table form

### ISSUE THREAD

**Issue by sayanee** [anujdeshpande/awesome-hardware-production#4]
Looking at some of the most active awesome repositories such as [awesome-python](https://github.com/vinta/awesome-python). [awesome-go](https://github.com/avelino/awesome-go) and [awesome-vue](https://github.com/vuejs/awesome-vue), they are simply presented in list form, not a table.

Some advantages of putting in list form include:

- Less visual clutter
- Less redundant info such as author
- More simple with the title hyperlinked to the link directly, instead of another column

What do you guys think @anujdeshpande @notthetup 😊 I can send a separate pull request on this 🙇‍♀️

**Comment by notthetup** [comment]
Tables are also hard to manipulate lists are simpler.

**Comment by anujdeshpande** [comment]
Looks so much cleaner
